import {
    Robot,
    DeviceMobile,
    ChatDots,
    ChatCircle,
    Broadcast,
    CalendarCheck,
    ArrowClockwise,
    MonitorPlay,
    Pulse,
    TrendUp,
    Shield,
    Lock,
    Bell,
    Gear,
    Lightning,
    Users,
    ChartBar,
    Envelope,
    Clock,
    Globe,
    Star,
    Rocket,
    Target,
    MagicWand,
    Database,
    Cloud,
    Link,
    Sparkle,
    Eye,
    CheckCircle,
    Phone,
    PaperPlaneRight,
    ListChecks,
    Funnel,
    Brain,
    Wrench,
    Plug,
    FileText,
    Tag,
    Megaphone,
    UserCircle,
    Headset,
    ShoppingCart,
    CreditCard,
    MapPin,
    Image,
    Camera,
    Heart,
} from '@phosphor-icons/react'

// Curated icon list for CMS icon picker
// Each entry: [IconComponent, displayLabel]
export const ICON_LIST: [string, React.ElementType, string][] = [
    // Communication
    ['ChatDots', ChatDots, 'Chat'],
    ['ChatCircle', ChatCircle, 'Chat Bulat'],
    ['Envelope', Envelope, 'Email'],
    ['Phone', Phone, 'Telepon'],
    ['Megaphone', Megaphone, 'Megafon'],
    ['Broadcast', Broadcast, 'Broadcast'],
    ['PaperPlaneRight', PaperPlaneRight, 'Kirim'],
    ['Headset', Headset, 'Support'],
    // Automation & Tech
    ['Robot', Robot, 'Robot'],
    ['Lightning', Lightning, 'Kilat'],
    ['Gear', Gear, 'Pengaturan'],
    ['MagicWand', MagicWand, 'Sihir'],
    ['ArrowClockwise', ArrowClockwise, 'Refresh'],
    ['Clock', Clock, 'Waktu'],
    ['CalendarCheck', CalendarCheck, 'Jadwal'],
    ['Brain', Brain, 'AI / Otak'],
    ['Sparkle', Sparkle, 'Sparkle'],
    // Data & Analytics
    ['ChartBar', ChartBar, 'Grafik'],
    ['TrendUp', TrendUp, 'Tren Naik'],
    ['Pulse', Pulse, 'Monitor'],
    ['Database', Database, 'Database'],
    ['Funnel', Funnel, 'Filter'],
    ['ListChecks', ListChecks, 'Checklist'],
    ['FileText', FileText, 'Dokumen'],
    ['Tag', Tag, 'Label'],
    // Security & Trust
    ['Shield', Shield, 'Keamanan'],
    ['Lock', Lock, 'Kunci'],
    ['CheckCircle', CheckCircle, 'Centang'],
    ['Star', Star, 'Bintang'],
    ['Eye', Eye, 'Lihat'],
    ['Heart', Heart, 'Favorit'],
    // People & Business
    ['Users', Users, 'Tim'],
    ['UserCircle', UserCircle, 'Profil'],
    ['Target', Target, 'Target'],
    ['ShoppingCart', ShoppingCart, 'Keranjang'],
    ['CreditCard', CreditCard, 'Pembayaran'],
    // Platform & Device
    ['DeviceMobile', DeviceMobile, 'HP'],
    ['MonitorPlay', MonitorPlay, 'Dashboard'],
    ['Globe', Globe, 'Web'],
    ['Cloud', Cloud, 'Cloud'],
    ['Plug', Plug, 'Integrasi'],
    ['Link', Link, 'Link'],
    ['Bell', Bell, 'Notifikasi'],
    ['MapPin', MapPin, 'Lokasi'],
    // General
    ['Rocket', Rocket, 'Roket'],
    ['Wrench', Wrench, 'Tools'],
    ['Image', Image, 'Gambar'],
    ['Camera', Camera, 'Kamera'],
]

// Fast lookup: name → component
export const ICON_MAP: Record<string, React.ElementType> = Object.fromEntries(
    ICON_LIST.map(([name, comp]) => [name, comp])
)
